#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon May 15 08:08:39 UTC 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 16306101acd8473681b56004b7bbddbe --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot multicycleconnection_behav xil_defaultlib.multicycleconnection -log elaborate.log"
xelab -wto 16306101acd8473681b56004b7bbddbe --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot multicycleconnection_behav xil_defaultlib.multicycleconnection -log elaborate.log

